name: deploy-docker-image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-arm64:
    name: Build and Push ARM64
    runs-on: [self-hosted, linux, ARM64]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to GitHub CR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Versions
        id: versions
        run: |
          VERSION=$(awk -F '"' '/^version/ {print $2}' Cargo.toml)
          echo "PUMPKIN_VERSION=$(echo $VERSION | cut -d '+' -f 1)" >> $GITHUB_ENV
          echo "MC_VERSION=$(echo $VERSION | cut -d '+' -f 2)" >> $GITHUB_ENV

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest
            type=sha
            type=raw,value=mc${{ env.MC_VERSION }}
            type=raw,value=${{ env.PUMPKIN_VERSION }}
            type=raw,value=mc${{ env.MC_VERSION }}-${{ env.PUMPKIN_VERSION }}

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build and Push ARM64
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

  build-amd64:
    name: Build and Push AMD64
    runs-on: [self-hosted, windows, x64]  # Adjust labels to match your runner's actual labels

    needs: build-arm64

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to GitHub CR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Versions
        id: versions
        shell: bash
        run: |
          VERSION=$(awk -F '"' '/^version/ {print $2}' Cargo.toml)
          echo "PUMPKIN_VERSION=$(echo $VERSION | cut -d '+' -f 1)" >> $GITHUB_ENV
          echo "MC_VERSION=$(echo $VERSION | cut -d '+' -f 2)" >> $GITHUB_ENV

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest
            type=sha
            type=raw,value=mc${{ env.MC_VERSION }}
            type=raw,value=${{ env.PUMPKIN_VERSION }}
            type=raw,value=mc${{ env.MC_VERSION }}-${{ env.PUMPKIN_VERSION }}

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and Push AMD64
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
